# Generated by Django 4.0.2 on 2022-02-17 15:40

import auctionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(upload_to=auctionApp.models.user_directory_path),
        ),
    ]
