# Generated by Django 4.0.2 on 2022-02-17 15:46

import auctionApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0003_remove_image_image_name_alter_image_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(default=0, upload_to=auctionApp.models.user_directory_path),
        ),
    ]
