# Generated by Django 4.0.2 on 2022-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0005_image_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_day', models.DateField()),
                ('bid_start_time', models.TimeField()),
                ('bid_end_time', models.TimeField()),
            ],
        ),
    ]
