# Generated by Django 4.0.2 on 2022-02-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0007_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_bid_time',
        ),
        migrations.DeleteModel(
            name='BiddingTime',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
