# Generated by Django 4.0.2 on 2022-02-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0009_biddingtime_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
