# Generated by Django 4.0.2 on 2022-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0011_alter_product_category_alter_product_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.IntegerField()),
                ('product_name', models.IntegerField()),
                ('bid_amount', models.FloatField()),
                ('bid_exact_time', models.TimeField(auto_now=True)),
                ('bid_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
