# Generated by Django 4.0.2 on 2022-02-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0012_biddingamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddingamount',
            name='bid_date',
        ),
        migrations.RemoveField(
            model_name='biddingamount',
            name='bid_exact_time',
        ),
    ]
