# Generated by Django 4.0.2 on 2022-03-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0013_remove_biddingamount_bid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'seller'), (2, 'buyer')], default=1),
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
